package category

// Blank imports to ensure all dependent modules register their SQL migrations
// during tests. Mirrors internal/modules.go to ensure correct migration order.
import (
	_ "github.com/Mininglamp-OSS/octo-server/modules/agentmailgateway"
	_ "github.com/Mininglamp-OSS/octo-server/modules/ai_team"
	_ "github.com/Mininglamp-OSS/octo-server/modules/app_bot"
	_ "github.com/Mininglamp-OSS/octo-server/modules/backup"
	_ "github.com/Mininglamp-OSS/octo-server/modules/base"
	_ "github.com/Mininglamp-OSS/octo-server/modules/bot_api"
	_ "github.com/Mininglamp-OSS/octo-server/modules/bot_mention"
	_ "github.com/Mininglamp-OSS/octo-server/modules/bot_provision"
	_ "github.com/Mininglamp-OSS/octo-server/modules/bot_task"
	_ "github.com/Mininglamp-OSS/octo-server/modules/botfather"
	_ "github.com/Mininglamp-OSS/octo-server/modules/card_template_catalog"
	_ "github.com/Mininglamp-OSS/octo-server/modules/channel"
	_ "github.com/Mininglamp-OSS/octo-server/modules/common"
	_ "github.com/Mininglamp-OSS/octo-server/modules/file"
	_ "github.com/Mininglamp-OSS/octo-server/modules/group"
	_ "github.com/Mininglamp-OSS/octo-server/modules/incomingwebhook"
	_ "github.com/Mininglamp-OSS/octo-server/modules/integration"
	_ "github.com/Mininglamp-OSS/octo-server/modules/internal_resolve"
	_ "github.com/Mininglamp-OSS/octo-server/modules/message"
	_ "github.com/Mininglamp-OSS/octo-server/modules/messages_search"
	_ "github.com/Mininglamp-OSS/octo-server/modules/notification"
	_ "github.com/Mininglamp-OSS/octo-server/modules/notify"
	_ "github.com/Mininglamp-OSS/octo-server/modules/oidc"
	_ "github.com/Mininglamp-OSS/octo-server/modules/opanalytics"
	_ "github.com/Mininglamp-OSS/octo-server/modules/openapi"
	_ "github.com/Mininglamp-OSS/octo-server/modules/project"
	_ "github.com/Mininglamp-OSS/octo-server/modules/qrcode"
	_ "github.com/Mininglamp-OSS/octo-server/modules/report"
	_ "github.com/Mininglamp-OSS/octo-server/modules/robot"
	_ "github.com/Mininglamp-OSS/octo-server/modules/search"
	_ "github.com/Mininglamp-OSS/octo-server/modules/space"
	_ "github.com/Mininglamp-OSS/octo-server/modules/statistics"
	_ "github.com/Mininglamp-OSS/octo-server/modules/sticker"
	_ "github.com/Mininglamp-OSS/octo-server/modules/thread"
	_ "github.com/Mininglamp-OSS/octo-server/modules/user"
	_ "github.com/Mininglamp-OSS/octo-server/modules/usersecret"
	_ "github.com/Mininglamp-OSS/octo-server/modules/voice_adapter"
	_ "github.com/Mininglamp-OSS/octo-server/modules/webhook"
	_ "github.com/Mininglamp-OSS/octo-server/modules/workplace"
)
