package authz

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type generatedContract struct {
	SchemaVersion      int                `json:"schema_version"`
	ContentHash        string             `json:"content_hash,omitempty"`
	Permissions        []Permission       `json:"permissions"`
	LegacyCapabilities []LegacyCapability `json:"legacy_capabilities"`
	GateSites          []GateSite         `json:"gate_sites"`
	Operations         []Operation        `json:"operations"`
}

func GenerateArtifacts(manifest *Manifest) ([]byte, []byte, error) {
	if err := ValidateManifest(manifest); err != nil {
		return nil, nil, err
	}
	if err := ValidateCriticalPermissions(manifest); err != nil {
		return nil, nil, err
	}
	normalized := normalizedContract(manifest)
	canonical, err := json.Marshal(normalized)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal canonical contract: %w", err)
	}
	hash := sha256.Sum256(canonical)
	normalized.ContentHash = hex.EncodeToString(hash[:])
	jsonOutput, err := json.MarshalIndent(normalized, "", "  ")
	if err != nil {
		return nil, nil, fmt.Errorf("marshal generated JSON: %w", err)
	}
	jsonOutput = append(jsonOutput, '\n')

	goOutput, err := generateGo(normalized)
	if err != nil {
		return nil, nil, err
	}
	return goOutput, jsonOutput, nil
}

func WriteGeneratedFiles(manifestPath, goOutputPath, jsonOutputPath string) error {
	manifest, err := LoadManifest(manifestPath)
	if err != nil {
		return err
	}
	goOutput, jsonOutput, err := GenerateArtifacts(manifest)
	if err != nil {
		return err
	}
	if err := writeAtomic(goOutputPath, goOutput); err != nil {
		return err
	}
	if err := writeAtomic(jsonOutputPath, jsonOutput); err != nil {
		return err
	}
	return nil
}

func CheckGeneratedFiles(manifestPath, goOutputPath, jsonOutputPath string) error {
	manifest, err := LoadManifest(manifestPath)
	if err != nil {
		return err
	}
	wantGo, wantJSON, err := GenerateArtifacts(manifest)
	if err != nil {
		return err
	}
	for path, want := range map[string][]byte{goOutputPath: wantGo, jsonOutputPath: wantJSON} {
		got, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated file %s: %w", path, err)
		}
		if !bytes.Equal(got, want) {
			return fmt.Errorf("generated file drift: %s", path)
		}
	}
	return nil
}

func normalizedContract(manifest *Manifest) generatedContract {
	result := generatedContract{
		SchemaVersion:      manifest.SchemaVersion,
		Permissions:        append([]Permission(nil), manifest.Permissions...),
		LegacyCapabilities: append([]LegacyCapability(nil), manifest.LegacyCapabilities...),
		GateSites:          append([]GateSite(nil), manifest.GateSites...),
		Operations:         append([]Operation(nil), manifest.Operations...),
	}
	sort.Slice(result.Permissions, func(i, j int) bool { return result.Permissions[i].Key < result.Permissions[j].Key })
	sort.Slice(result.LegacyCapabilities, func(i, j int) bool { return result.LegacyCapabilities[i].Key < result.LegacyCapabilities[j].Key })
	sort.Slice(result.GateSites, func(i, j int) bool { return result.GateSites[i].Source < result.GateSites[j].Source })
	sort.Slice(result.Operations, func(i, j int) bool { return result.Operations[i].ID < result.Operations[j].ID })
	for i := range result.LegacyCapabilities {
		result.LegacyCapabilities[i].Permissions = append([]string(nil), result.LegacyCapabilities[i].Permissions...)
		sort.Strings(result.LegacyCapabilities[i].Permissions)
	}
	for i := range result.Operations {
		result.Operations[i].GateSites = append([]string(nil), result.Operations[i].GateSites...)
		sort.Strings(result.Operations[i].GateSites)
	}
	return result
}

func generateGo(contract generatedContract) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by tools/manager-permission-gen; DO NOT EDIT.\n\n")
	output.WriteString("package authz\n\n")
	fmt.Fprintf(&output, "const PermissionContractSchemaVersion = %d\n\n", contract.SchemaVersion)
	output.WriteString("const (\n")
	identifiers := make(map[string]string, len(contract.Permissions))
	for _, permission := range contract.Permissions {
		identifier := "Permission" + permissionIdentifier(permission.Key)
		if previous, exists := identifiers[identifier]; exists {
			return nil, fmt.Errorf("permission keys %q and %q generate duplicate Go identifier %q", previous, permission.Key, identifier)
		}
		identifiers[identifier] = permission.Key
		fmt.Fprintf(&output, "\t%s = %q\n", identifier, permission.Key)
	}
	output.WriteString(")\n\n")
	output.WriteString("type GeneratedPermissionMetadata struct {\n")
	output.WriteString("\tResource string\n\tAction string\n\tDescription string\n\tSensitivity Sensitivity\n}\n\n")
	output.WriteString("var GeneratedPermissions = map[string]GeneratedPermissionMetadata{\n")
	for _, permission := range contract.Permissions {
		fmt.Fprintf(&output, "\t%q: {Resource: %q, Action: %q, Description: %q, Sensitivity: %q},\n",
			permission.Key, permission.Resource, permission.Action, permission.Description, permission.Sensitivity)
	}
	output.WriteString("}\n\n")
	output.WriteString("func IsKnownPermission(key string) bool {\n\t_, ok := GeneratedPermissions[key]\n\treturn ok\n}\n")
	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return formatted, nil
}

func permissionIdentifier(key string) string {
	var output strings.Builder
	upper := true
	for _, value := range key {
		if value == '.' || value == '_' || value == '-' {
			upper = true
			continue
		}
		if upper {
			value = unicode.ToUpper(value)
			upper = false
		}
		output.WriteRune(value)
	}
	return output.String()
}

func writeAtomic(path string, contents []byte) error {
	directory := filepath.Dir(path)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create output directory %s: %w", directory, err)
	}
	temporary, err := os.CreateTemp(directory, ".manager-permission-*")
	if err != nil {
		return fmt.Errorf("create temporary output for %s: %w", path, err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if _, err := temporary.Write(contents); err != nil {
		temporary.Close()
		return fmt.Errorf("write temporary output for %s: %w", path, err)
	}
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return fmt.Errorf("chmod temporary output for %s: %w", path, err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close temporary output for %s: %w", path, err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace generated file %s: %w", path, err)
	}
	return nil
}
