// Code generated by tools/manager-permission-gen; DO NOT EDIT.

package authz

const PermissionContractSchemaVersion = 1

const (
	PermissionAppBotAvatarUpdate         = "app_bot.avatar.update"
	PermissionAppBotCreate               = "app_bot.create"
	PermissionAppBotDelete               = "app_bot.delete"
	PermissionAppBotPublish              = "app_bot.publish"
	PermissionAppBotRead                 = "app_bot.read"
	PermissionAppBotTokenReveal          = "app_bot.token.reveal"
	PermissionAppBotTokenRotate          = "app_bot.token.rotate"
	PermissionAppBotUnpublish            = "app_bot.unpublish"
	PermissionAppBotUpdate               = "app_bot.update"
	PermissionAppConfigRead              = "app_config.read"
	PermissionAppConfigWrite             = "app_config.write"
	PermissionAppModuleRead              = "app_module.read"
	PermissionAppModuleWrite             = "app_module.write"
	PermissionAppVersionRead             = "app_version.read"
	PermissionAppVersionWrite            = "app_version.write"
	PermissionBackupConfigRead           = "backup.config.read"
	PermissionBackupConfigTest           = "backup.config.test"
	PermissionBackupConfigWrite          = "backup.config.write"
	PermissionBackupDownload             = "backup.download"
	PermissionBackupHistoryDelete        = "backup.history.delete"
	PermissionBackupHistoryRead          = "backup.history.read"
	PermissionBackupStatusRead           = "backup.status.read"
	PermissionBackupTrigger              = "backup.trigger"
	PermissionCardTemplateActivate       = "card_template.activate"
	PermissionCardTemplateAuditRead      = "card_template.audit.read"
	PermissionCardTemplateBlock          = "card_template.block"
	PermissionCardTemplatePublish        = "card_template.publish"
	PermissionCardTemplateRead           = "card_template.read"
	PermissionCardTemplateRollback       = "card_template.rollback"
	PermissionCardTemplateValidate       = "card_template.validate"
	PermissionDashboardEtlTrigger        = "dashboard.etl.trigger"
	PermissionDashboardRead              = "dashboard.read"
	PermissionExpertRead                 = "expert.read"
	PermissionExpertWrite                = "expert.write"
	PermissionGroupMemberRemove          = "group.member.remove"
	PermissionGroupRead                  = "group.read"
	PermissionGroupWrite                 = "group.write"
	PermissionIntegrationOidcClientWrite = "integration.oidc_client.write"
	PermissionMcpRead                    = "mcp.read"
	PermissionMcpWrite                   = "mcp.write"
	PermissionMessageBroadcastSend       = "message.broadcast.send"
	PermissionMessageDelete              = "message.delete"
	PermissionMessageDirectHistoryRead   = "message.direct_history.read"
	PermissionMessageHistoryRead         = "message.history.read"
	PermissionMessageImpersonatedSend    = "message.impersonated.send"
	PermissionMessageOutboundRead        = "message.outbound.read"
	PermissionMessageProhibitedWordRead  = "message.prohibited_word.read"
	PermissionMessageProhibitedWordWrite = "message.prohibited_word.write"
	PermissionMessageSend                = "message.send"
	PermissionReportRead                 = "report.read"
	PermissionRobotDelete                = "robot.delete"
	PermissionRobotMenuRead              = "robot.menu.read"
	PermissionRobotMenuWrite             = "robot.menu.write"
	PermissionRobotRead                  = "robot.read"
	PermissionRobotStatusWrite           = "robot.status.write"
	PermissionRobotTokenRevoke           = "robot.token.revoke"
	PermissionRobotUpdate                = "robot.update"
	PermissionSkillRead                  = "skill.read"
	PermissionSkillWrite                 = "skill.write"
	PermissionSpaceCreate                = "space.create"
	PermissionSpaceDestroy               = "space.destroy"
	PermissionSpaceInviteWrite           = "space.invite.write"
	PermissionSpaceJoinRequestWrite      = "space.join_request.write"
	PermissionSpaceMemberAdd             = "space.member.add"
	PermissionSpaceMemberRemove          = "space.member.remove"
	PermissionSpaceMemberRoleWrite       = "space.member.role.write"
	PermissionSpaceOwnerInviteWrite      = "space.owner_invite.write"
	PermissionSpaceRead                  = "space.read"
	PermissionSpaceStatusWrite           = "space.status.write"
	PermissionSpaceUpdate                = "space.update"
	PermissionStatisticsRead             = "statistics.read"
	PermissionSystemSettingRead          = "system_setting.read"
	PermissionSystemSettingWrite         = "system_setting.write"
	PermissionUserAdminManage            = "user.admin.manage"
	PermissionUserCreate                 = "user.create"
	PermissionUserFixedRoleRead          = "user.fixed_role.read"
	PermissionUserFixedRoleWrite         = "user.fixed_role.write"
	PermissionUserPasswordReset          = "user.password.reset"
	PermissionUserPasswordUpdate         = "user.password.update"
	PermissionUserPhoneShadowBackfill    = "user.phone_shadow.backfill"
	PermissionUserPhoneShadowRead        = "user.phone_shadow.read"
	PermissionUserRead                   = "user.read"
	PermissionUserStatusWrite            = "user.status.write"
	PermissionWorkplaceAppRead           = "workplace.app.read"
	PermissionWorkplaceAppWrite          = "workplace.app.write"
	PermissionWorkplaceBannerRead        = "workplace.banner.read"
	PermissionWorkplaceBannerWrite       = "workplace.banner.write"
	PermissionWorkplaceCategoryRead      = "workplace.category.read"
	PermissionWorkplaceCategoryWrite     = "workplace.category.write"
)

type GeneratedPermissionMetadata struct {
	Resource    string
	Action      string
	Description string
	Sensitivity Sensitivity
}

var GeneratedPermissions = map[string]GeneratedPermissionMetadata{
	"app_bot.avatar.update":         {Resource: "app_bot_avatar", Action: "update", Description: "以全局管理员身份修改 App Bot 头像", Sensitivity: "elevated"},
	"app_bot.create":                {Resource: "app_bot", Action: "create", Description: "创建平台 App Bot", Sensitivity: "elevated"},
	"app_bot.delete":                {Resource: "app_bot", Action: "delete", Description: "删除平台 App Bot", Sensitivity: "critical"},
	"app_bot.publish":               {Resource: "app_bot", Action: "publish", Description: "发布平台 App Bot", Sensitivity: "elevated"},
	"app_bot.read":                  {Resource: "app_bot", Action: "read", Description: "查看平台 App Bot", Sensitivity: "standard"},
	"app_bot.token.reveal":          {Resource: "app_bot_token", Action: "reveal", Description: "查看平台 App Bot 明文 token", Sensitivity: "critical"},
	"app_bot.token.rotate":          {Resource: "app_bot_token", Action: "rotate", Description: "轮换平台 App Bot token", Sensitivity: "critical"},
	"app_bot.unpublish":             {Resource: "app_bot", Action: "unpublish", Description: "下架平台 App Bot", Sensitivity: "elevated"},
	"app_bot.update":                {Resource: "app_bot", Action: "update", Description: "修改平台 App Bot", Sensitivity: "elevated"},
	"app_config.read":               {Resource: "app_config", Action: "read", Description: "查看应用配置", Sensitivity: "standard"},
	"app_config.write":              {Resource: "app_config", Action: "write", Description: "修改应用配置", Sensitivity: "elevated"},
	"app_module.read":               {Resource: "app_module", Action: "read", Description: "查看应用模块", Sensitivity: "standard"},
	"app_module.write":              {Resource: "app_module", Action: "write", Description: "维护应用模块", Sensitivity: "elevated"},
	"app_version.read":              {Resource: "app_version", Action: "read", Description: "查看应用版本", Sensitivity: "standard"},
	"app_version.write":             {Resource: "app_version", Action: "write", Description: "发布应用版本", Sensitivity: "elevated"},
	"backup.config.read":            {Resource: "backup_config", Action: "read", Description: "查看备份配置", Sensitivity: "standard"},
	"backup.config.test":            {Resource: "backup_config", Action: "test", Description: "测试备份存储连接", Sensitivity: "elevated"},
	"backup.config.write":           {Resource: "backup_config", Action: "write", Description: "修改备份配置", Sensitivity: "elevated"},
	"backup.download":               {Resource: "backup", Action: "download", Description: "下载备份文件", Sensitivity: "critical"},
	"backup.history.delete":         {Resource: "backup_history", Action: "delete", Description: "删除备份历史", Sensitivity: "elevated"},
	"backup.history.read":           {Resource: "backup_history", Action: "read", Description: "查看备份历史", Sensitivity: "standard"},
	"backup.status.read":            {Resource: "backup_status", Action: "read", Description: "查看备份状态", Sensitivity: "standard"},
	"backup.trigger":                {Resource: "backup", Action: "trigger", Description: "手动触发备份", Sensitivity: "elevated"},
	"card_template.activate":        {Resource: "card_template", Action: "activate", Description: "切换卡片模板活动版本", Sensitivity: "elevated"},
	"card_template.audit.read":      {Resource: "card_template_audit", Action: "read", Description: "查看卡片模板审计记录", Sensitivity: "standard"},
	"card_template.block":           {Resource: "card_template", Action: "block", Description: "封禁卡片模板", Sensitivity: "elevated"},
	"card_template.publish":         {Resource: "card_template", Action: "publish", Description: "发布卡片模板", Sensitivity: "elevated"},
	"card_template.read":            {Resource: "card_template", Action: "read", Description: "查看卡片模板", Sensitivity: "standard"},
	"card_template.rollback":        {Resource: "card_template", Action: "rollback", Description: "回滚卡片模板", Sensitivity: "critical"},
	"card_template.validate":        {Resource: "card_template", Action: "validate", Description: "验证卡片模板", Sensitivity: "standard"},
	"dashboard.etl.trigger":         {Resource: "dashboard_etl", Action: "trigger", Description: "手动触发看板 ETL", Sensitivity: "elevated"},
	"dashboard.read":                {Resource: "dashboard", Action: "read", Description: "查看运营看板", Sensitivity: "standard"},
	"expert.read":                   {Resource: "expert", Action: "read", Description: "查看专家市场", Sensitivity: "standard"},
	"expert.write":                  {Resource: "expert", Action: "write", Description: "维护专家市场", Sensitivity: "elevated"},
	"group.member.remove":           {Resource: "group_member", Action: "remove", Description: "以全局管理员身份移除群成员", Sensitivity: "elevated"},
	"group.read":                    {Resource: "group", Action: "read", Description: "查看全局群组信息", Sensitivity: "standard"},
	"group.write":                   {Resource: "group", Action: "write", Description: "执行全局群组管理", Sensitivity: "elevated"},
	"integration.oidc_client.write": {Resource: "oidc_client", Action: "write", Description: "修改 OIDC 客户端配置", Sensitivity: "critical"},
	"mcp.read":                      {Resource: "mcp", Action: "read", Description: "查看系统 MCP", Sensitivity: "standard"},
	"mcp.write":                     {Resource: "mcp", Action: "write", Description: "维护系统 MCP", Sensitivity: "elevated"},
	"message.broadcast.send":        {Resource: "message", Action: "broadcast", Description: "向全部用户广播消息", Sensitivity: "critical"},
	"message.delete":                {Resource: "message", Action: "delete", Description: "删除消息", Sensitivity: "critical"},
	"message.direct_history.read":   {Resource: "direct_message_history", Action: "read", Description: "查看任意私聊历史", Sensitivity: "critical"},
	"message.history.read":          {Resource: "message_history", Action: "read", Description: "查看全局消息历史", Sensitivity: "elevated"},
	"message.impersonated.send":     {Resource: "message", Action: "impersonated_send", Description: "代用户向好友发送消息", Sensitivity: "critical"},
	"message.outbound.read":         {Resource: "message", Action: "read", Description: "查看管理消息发送记录", Sensitivity: "standard"},
	"message.prohibited_word.read":  {Resource: "prohibited_word", Action: "read", Description: "查看违禁词", Sensitivity: "standard"},
	"message.prohibited_word.write": {Resource: "prohibited_word", Action: "write", Description: "维护违禁词", Sensitivity: "elevated"},
	"message.send":                  {Resource: "message", Action: "send", Description: "发送管理消息", Sensitivity: "elevated"},
	"report.read":                   {Resource: "report", Action: "read", Description: "查看举报列表", Sensitivity: "standard"},
	"robot.delete":                  {Resource: "robot", Action: "delete", Description: "删除平台机器人", Sensitivity: "critical"},
	"robot.menu.read":               {Resource: "robot_menu", Action: "read", Description: "查看机器人菜单", Sensitivity: "standard"},
	"robot.menu.write":              {Resource: "robot_menu", Action: "write", Description: "删除机器人菜单", Sensitivity: "elevated"},
	"robot.read":                    {Resource: "robot", Action: "read", Description: "查看平台机器人", Sensitivity: "standard"},
	"robot.status.write":            {Resource: "robot", Action: "status_write", Description: "修改机器人状态", Sensitivity: "elevated"},
	"robot.token.revoke":            {Resource: "robot_token", Action: "revoke", Description: "吊销机器人 token", Sensitivity: "critical"},
	"robot.update":                  {Resource: "robot", Action: "update", Description: "修改平台机器人", Sensitivity: "elevated"},
	"skill.read":                    {Resource: "skill", Action: "read", Description: "查看系统 Skill", Sensitivity: "standard"},
	"skill.write":                   {Resource: "skill", Action: "write", Description: "维护系统 Skill", Sensitivity: "elevated"},
	"space.create":                  {Resource: "space", Action: "create", Description: "代建 Space", Sensitivity: "elevated"},
	"space.destroy":                 {Resource: "space", Action: "destroy", Description: "强制解散 Space", Sensitivity: "critical"},
	"space.invite.write":            {Resource: "space_invite", Action: "write", Description: "维护 Space 邀请码", Sensitivity: "elevated"},
	"space.join_request.write":      {Resource: "space_join_request", Action: "write", Description: "审批 Space 加入申请", Sensitivity: "elevated"},
	"space.member.add":              {Resource: "space_member", Action: "add", Description: "强制添加 Space 成员", Sensitivity: "elevated"},
	"space.member.remove":           {Resource: "space_member", Action: "remove", Description: "强制移除 Space 成员", Sensitivity: "critical"},
	"space.member.role.write":       {Resource: "space_member", Action: "role_write", Description: "修改 Space 成员角色", Sensitivity: "critical"},
	"space.owner_invite.write":      {Resource: "space_owner_invite", Action: "write", Description: "维护 Space owner 邮件邀请", Sensitivity: "critical"},
	"space.read":                    {Resource: "space", Action: "read", Description: "查看全局 Space 信息", Sensitivity: "standard"},
	"space.status.write":            {Resource: "space", Action: "status_write", Description: "封禁或解禁 Space", Sensitivity: "critical"},
	"space.update":                  {Resource: "space", Action: "update", Description: "修改 Space 基础信息", Sensitivity: "elevated"},
	"statistics.read":               {Resource: "statistics", Action: "read", Description: "查看全局统计数据", Sensitivity: "standard"},
	"system_setting.read":           {Resource: "system_setting", Action: "read", Description: "查看系统设置", Sensitivity: "elevated"},
	"system_setting.write":          {Resource: "system_setting", Action: "write", Description: "修改或测试系统设置", Sensitivity: "critical"},
	"user.admin.manage":             {Resource: "admin_user", Action: "manage", Description: "管理管理员账号", Sensitivity: "critical"},
	"user.create":                   {Resource: "user", Action: "create", Description: "创建用户", Sensitivity: "elevated"},
	"user.fixed_role.read":          {Resource: "fixed_manager_role", Action: "read", Description: "查看固定管理角色成员", Sensitivity: "critical"},
	"user.fixed_role.write":         {Resource: "fixed_manager_role", Action: "write", Description: "授予或撤销固定管理角色", Sensitivity: "critical"},
	"user.password.reset":           {Resource: "user_password", Action: "reset", Description: "重置用户密码", Sensitivity: "critical"},
	"user.password.update":          {Resource: "user_password", Action: "update", Description: "修改用户密码", Sensitivity: "critical"},
	"user.phone_shadow.backfill":    {Resource: "phone_shadow", Action: "backfill", Description: "执行手机号影子列回填", Sensitivity: "critical"},
	"user.phone_shadow.read":        {Resource: "phone_shadow", Action: "read", Description: "查看手机号影子列回填状态", Sensitivity: "elevated"},
	"user.read":                     {Resource: "user", Action: "read", Description: "查看全局用户信息", Sensitivity: "standard"},
	"user.status.write":             {Resource: "user", Action: "status_write", Description: "封禁或解禁用户", Sensitivity: "elevated"},
	"workplace.app.read":            {Resource: "workplace_app", Action: "read", Description: "查看工作台应用", Sensitivity: "standard"},
	"workplace.app.write":           {Resource: "workplace_app", Action: "write", Description: "维护工作台应用", Sensitivity: "elevated"},
	"workplace.banner.read":         {Resource: "workplace_banner", Action: "read", Description: "查看工作台横幅", Sensitivity: "standard"},
	"workplace.banner.write":        {Resource: "workplace_banner", Action: "write", Description: "维护工作台横幅", Sensitivity: "elevated"},
	"workplace.category.read":       {Resource: "workplace_category", Action: "read", Description: "查看工作台分类", Sensitivity: "standard"},
	"workplace.category.write":      {Resource: "workplace_category", Action: "write", Description: "维护工作台分类", Sensitivity: "elevated"},
}

func IsKnownPermission(key string) bool {
	_, ok := GeneratedPermissions[key]
	return ok
}
