package botfather

import (
	"fmt"

	"github.com/Mininglamp-OSS/octo-lib/config"
	"github.com/Mininglamp-OSS/octo-server/modules/user"
	"go.uber.org/zap"
)

// MintBotResult is the result of a successful OBO bot mint.
type MintBotResult struct {
	BotUID   string // robot_id, also used as IM uid
	BotToken string // bf_xxx token for /v1/bot/* authentication
}

// MintBotOBO creates a bot on behalf of ownerUID, scoped to the given space.
//
// Unlike the IM /newbot flow (which has space fallback and command-handler
// state), this is a non-interactive call intended for service-to-service use
// (e.g. the runtime module creating a bot automatically when a managed agent
// is provisioned). spaceID is required — no fallback to creator's first space.
//
// botToken must be generated by the server-side caller before invoking this
// helper. Public HTTP callers do not choose bot credentials.
//
// Steps mirror tryCreateBotCore + the post-create block of createBot:
//  1. create app (idempotent on robot_id)
//  2. insert robot row
//  3. add user (Robot=1)
//  4. add bot to space_member (required; this is authorization state)
//  5. friend owner <-> bot bidirectional (logged-and-continue on failure)
func MintBotOBO(ctx *config.Context, ownerUID, spaceID, displayName, botToken string) (*MintBotResult, error) {
	if ownerUID == "" {
		return nil, fmt.Errorf("MintBotOBO: ownerUID required")
	}
	if spaceID == "" {
		return nil, fmt.Errorf("MintBotOBO: spaceID required (OBO mode has no fallback)")
	}
	if displayName == "" {
		return nil, fmt.Errorf("MintBotOBO: displayName required")
	}
	if botToken == "" {
		return nil, fmt.Errorf("MintBotOBO: botToken required")
	}

	h := newCommandHandler(ctx)

	robotID, err := h.createBotCoreWithRetry(ownerUID, displayName, botToken)
	if err != nil {
		return nil, fmt.Errorf("MintBotOBO: createBotCore: %w", err)
	}

	_, err = h.ctx.DB().InsertBySql(
		// is_bot 恒为 1：本路径插入的只可能是刚建出来的 bot。写字面量而不是像
		// modules/space 那样从 user 表派生，是因为此处 user 行的写入顺序不保证先于
		// 本语句，派生会静默取到 0，把 bot 错分成真人（见 space_member.is_bot 的迁移说明）。
		"INSERT IGNORE INTO space_member (space_id, uid, role, status, is_bot, created_at, updated_at) VALUES (?, ?, 0, 1, 1, NOW(), NOW())",
		spaceID, robotID,
	).Exec()
	if err != nil {
		h.Warn("MintBotOBO: bot 加入 Space 失败",
			zap.Error(err), zap.String("bot_uid", robotID), zap.String("space_id", spaceID))
		return nil, fmt.Errorf("MintBotOBO: add bot to space: %w", err)
	}

	if err := h.userService.AddFriend(ownerUID, &user.FriendReq{UID: ownerUID, ToUID: robotID}); err != nil {
		h.Warn("MintBotOBO: 好友 owner->bot 失败", zap.Error(err))
	}
	if err := h.userService.AddFriend(robotID, &user.FriendReq{UID: robotID, ToUID: ownerUID}); err != nil {
		h.Warn("MintBotOBO: 好友 bot->owner 失败", zap.Error(err))
	}
	h.fixFriendVersion(ownerUID, robotID)
	h.fixFriendVersion(robotID, ownerUID)

	return &MintBotResult{
		BotUID:   robotID,
		BotToken: botToken,
	}, nil
}
